### ISSUE TITLE
Petite erreur

### ISSUE THREAD

**Issue by Tchetchouille** [DigitalDW/meteor_blaze_kit#4]
Dans le readme, dans la partie sur les templates où tu expliques la logiques des boucles, tu écris "Donc le programme va afficher trois {{> liste}} puisque seulement trois éléments sont définit dans le JavaScript (lignes 31-40) ." Mais les trois éléments sont définis aux lignes 56-61.

**Comment by LRimaz** [comment]
Bien vu! c'est corrigé!
